# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d4efb01be4cd41a41360f21d9db9144e2cf73e64819a675345cd209126b1302abe5664def878e2f0c9ebc09b04776f2ddb0cc1d004e4d975e56d0805cc9a1b5

test:
  secret_key_base: 4e538175ee5d5bddf6318f80b00d54c9490303a659c5c0718ecce99cea3916a32fd9476ce03e562af77110ec6ec4fd2fafa37dfaa928b4e6ba2d08a28530357a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
